name: Java CI

on: 
  push:
    branches: 
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Run unit tests
        run: mvn test 

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Install the Application
        run: mvn clean install 

      - name: Terraform Destroy
        run: ( cd terraform; terraform destroy -auto-approve -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}' )

      - name: Terraform Init
        run: ( cd terraform; terraform destroy -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}' )

      - name: Terraform Apply
        run: ( cd terraform; terraform apply -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}' )