name: Terraform Apply
on: 
  push:
    branches: 
      - main

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: ( cd terraform ; terraform init -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}')

    - name: Terraform validation
      run: ( cd terraform ; terraform validate )

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: ( cd terraform ; terraform apply -auto-approve -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}')