name: Terraform Apply
on: 
  push:
    branches: 
      - main
      - dev

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: ( cd terraform ; terraform init -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}')

    - name: Terraform validation
      run: ( cd terraform ; terraform validate )

    - name: Terraform destroy
      run: ( cd terraform ; terraform destroy -auto-approve -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}')

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: ( cd terraform ; terraform apply -auto-approve -var 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}' -var 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}')